export const palette = {
    text: 'var(--clr-text)',
    textOnPrimary: 'var(--clr-text-on-primary)',
    textOnSecondary: 'var(--clr-text-on-secondary)',
    primary: 'var(--clr-primary)',
    primaryHover: 'var(--clr-primary-hover)',
    primaryBackgroundHover: 'var(--clr-primary-background-hover)',
    secondary: 'var(--clr-secondary)',
    secondaryHover: 'var(--clr-secondary-hover)',
    secondaryBackgroundHover: 'var(--clr-secondary-background-hover)',
    backgroundPage: 'var(--clr-background-page)',
    backgroundCard: 'var(--clr-background-card)',
    backgroundCardHover: 'var(--clr-background-card-hover)',
    control: 'var(--clr-control)',
    border: 'var(--clr-border)',
    borderFocus: 'var(--clr-border-focus)',
};
