import 'primereact/resources/themes/lara-dark-blue/theme.css';
import type { Metadata } from 'next';
import './globals.css';
import '../styles/clerk.scss';
import { initDatabase } from '@/database/appwrite';
import Script from 'next/script';
import { ClientProviders } from '@/app/clientProviders';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    if (!process.env.APPWRITE_DB_ID) {
        throw new Error('Cannot find process.env.APPWRITE_DB_ID');
    }

    await initDatabase(process.env.APPWRITE_DB_ID);

    return (
        <ClientProviders>
            <html lang="en">
                <head>
                    <Script id="google-maps-api">
                        {`
                        (g=>{var h,a,k,p="The Google Maps JavaScript API",c="google",l="importLibrary",q="__ib__",m=document,b=window;b=b[c]||(b[c]={});var d=b.maps||(b.maps={}),r=new Set,e=new URLSearchParams,u=()=>h||(h=new Promise(async(f,n)=>{await (a=m.createElement("script"));e.set("libraries",[...r]+"");for(k in g)e.set(k.replace(/[A-Z]/g,t=>"_"+t[0].toLowerCase()),g[k]);e.set("callback",c+".maps."+q);a.src=\`https://maps.\${c}apis.com/maps/api/js?\`+e;d[q]=f;a.onerror=()=>h=n(Error(p+" could not load."));a.nonce=m.querySelector("script[nonce]")?.nonce||"";m.head.append(a)}));d[l]?console.warn(p+" only loads once. Ignoring:",g):d[l]=(f,...n)=>r.add(f)&&u().then(()=>d[l](f,...n))})({
                        key: "${process.env.GOOGLE_MAPS_API_KEY}",
                        v: "weekly",
                    });
                        `}
                    </Script>
                </head>
                <body className={`dark text-white bg-page min-h-[100vh]`}>
                    {children}
                </body>
            </html>
        </ClientProviders>
    );
}
