import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { ClerkProvider } from '@clerk/nextjs';
import { dark } from '@clerk/themes';
import { Providers } from './providers';
import '../styles/clerk.scss';
import { initDatabase } from '@/database/appwrite';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    if (!process.env.APPWRITE_DB_ID) {
        throw new Error('Cannot find process.env.APPWRITE_DB_ID');
    }

    await initDatabase(process.env.APPWRITE_DB_ID);

    return (
        <ClerkProvider
            appearance={{
                baseTheme: dark,
            }}
        >
            <html lang="en">
                <body
                    className={`${inter.className} dark bg-background2 min-h-[100vh]`}
                >
                    {children}
                </body>
            </html>
        </ClerkProvider>
    );
}
