import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../globals.css';
import { Providers } from '../providers';
import '../../styles/clerk.scss';
import Navbar from '@/components/Navbar/navbar';
import React from 'react';
import dynamic from 'next/dynamic';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${inter.className} dark bg-background2 min-h-[100vh]`}
            >
                <Navbar />
                <Providers>{children}</Providers>
            </body>
        </html>
    );
}
